### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by p-j-smith** [epitools/napari-epitools#29]
[As mentioned](https://github.com/epitools/napari-epitools/pull/28#issuecomment-1453448837) in a previous pr, tests pass locally but CI is failing, possibly due to an issues with `pytest-xvfb`

**Comment by p-j-smith** [comment]
I think this issue might be to do with the [use of `thread_worker`](https://github.com/epitools/napari-epitools/blob/main/src/napari_epitools/_widget.py#L168) in the widgets. I think that the failure happens because the thread is still running when the test finishes and so the `QApplication` doesn't close nicely.

In the [test that adds the plugin dock widget to a napari viewer](https://github.com/epitools/napari-epitools/blob/main/src/napari_epitools/_tests/test_projection.py#L31), if you force the viewer to close at the end of the test then there's no error. To force a viewer to close after a test, [napari](https://github.com/napari/napari/blob/main/napari/_tests/test_view_layers.py#L183-L197) calls `viewer.close()` and then calls the garbage collector.

However, in napari's tests using a thread worker, this isn't necessary. Instead, they tell `qtbot` to [wait for the thread worker to finish](https://github.com/napari/napari/blob/main/napari/_tests/test_magicgui.py#L118).

Another option might be to set [`strict_qt=True`](https://github.com/napari/napari/blob/main/napari/utils/_testsupport.py#L149) when creating napari viewer for the test. This will make sure all widgets are closed in the test teardown

**Comment by paddyroddy** [comment]
Let's leave this open when #30 is merged - although maybe rename

**Comment by p-j-smith** [comment]
I renamed it...then thought a separate issue might be better

**Comment by paddyroddy** [comment]
Makes sense. Plus, you get that adrenalin rush from closing another issue 🥳
